[package]
name = "kms_sign"
version = "0.1.0"
edition = "2021"

[dependencies]
asn1 = "0.16.1"
aws-config = { version = "1.1.8", features = ["behavior-version-latest"] }
aws-sdk-kms = "1.17.0"
env-file-reader = "0.3.0"
home = "0.5.9"
toml = "0.8.11"
